apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: 397139394912.dkr.ecr.ap-south-1.amazonaws.com/employee-service:latest
        ports:
        - containerPort: 8080
